sudo: required
language: android
jdk: oraclejdk8
image: thyrlian/android-sdk

android:
    components:
        - tools
        - platform-tools
        # - build-tools-29.0.0
        # - build-tools-28.0.2
        - build-tools-27.0.2
        - android-27
        # - android-28
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-support
        - extra-android-m2repository
        # - addon-google_apis-google-28
        # - sys-img-armeabi-v7a-android-28
        - add-on
        - extra
licenses:
    - 'android-sdk-license-.+'

before_install:
#    - sudo apt-get update
#    - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev
#      libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
#    - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
#    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
#    - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
#    - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
#    - git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
#    - echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bash_profile
#    - source ~/.bash_profile
#    - pyenv versions
#    - pyenv install 3.6.1
#    - pyenv virtualenv 3.6.1 undang
#    - pyenv activate undang
#    - pip install -r requirements.txt
#    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
#    - sudo apt-get install nodejs
#    - sudo apt-get install build-essential
#    - PATH=$PATH:$JAVA_HOME/bin
#    - npm install appium
#    - npm install appium-doctor
#    - "./node_modules/.bin/appium-doctor"
#    - "./node_modules/.bin/appium --log-level info > appium_log.txt &"
    - sdkmanager tools
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "build-tools;android-27.0.2"

before_script:
    - echo y | sdkmanager "system-images;android-27;google_apis;armeabi-v7a"
    - echo "no" | avdmanager --verbose create avd -n PF -k "system-images;android-27;google_apis;armeabi-v7a" -b google_apis/armeabi-v7a -f
    # -k "system-images;android-25;google_apis;armeabi-v7a" --abi "google_apis;armeabi-v7a" --tag google_apis --device "pixel" --name PF --force 
    # - echo no | android create avd --force -n PF -t android-28 --abi armeabi-v7a
    - $ANDROID_HOME/emulator/emulator -avd PF -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - avd devices
    - adb install data/apps/falabellaApp.apk
    - "./gradlew assemble" # Build
    # - ./gradlew clean connectedCheck
    # - chmod +x ./gradlew
    # - ./gradlew connectedAndroidTest mergeAndroidReports --continue -PdisablePreDex --stacktrace
    - python3 -m pytest src/spec/* # Test

after_script:
    - cat ./appium_log.txt # Check appium log
